const quadrinhos = [
  {
    id: 1,
    titulo: "Batman: Ano Um",
    editora: "DC Comics",
    numero: 404,
    saga: "Ano Um",
    heroi: "Batman",
    autor: "Frank Miller",
    anoPublicacao: 1987,
    preco: 35.90,
  },
  {
    id: 2,
    titulo: "O Cavaleiro das Trevas",
    editora: "DC Comics",
    numero: 1,
    saga: "O Cavaleiro das Trevas",
    heroi: "Batman",
    autor: "Frank Miller",
    anoPublicacao: 1986,
    preco: 45.00,
  },
  {
    id: 3,
    titulo: "Crise nas Infinitas Terras",
    editora: "DC Comics",
    numero: 7,
    saga: "Crise nas Infinitas Terras",
    heroi: "Liga da Justiça",
    autor: "Marv Wolfman",
    anoPublicacao: 1985,
    preco: 50.00,
  },
  {
    id: 4,
    titulo: "Vingadores: A Queda",
    editora: "Marvel Comics",
    numero: 500,
    saga: "Vingadores: A Queda",
    heroi: "Vingadores",
    autor: "Brian Michael Bendis",
    anoPublicacao: 2004,
    preco: 28.50,
  },
  {
    id: 5,
    titulo: "Guerra Civil",
    editora: "Marvel Comics",
    numero: 1,
    saga: "Guerra Civil",
    heroi: "Homem de Ferro",
    autor: "Mark Millar",
    anoPublicacao: 2006,
    preco: 39.90,
  },
  {
    id: 6,
    titulo: "O Dia Mais Claro",
    editora: "DC Comics",
    numero: 0,
    saga: "O Dia Mais Claro",
    heroi: "Lanterna Verde",
    autor: "Geoff Johns",
    anoPublicacao: 2010,
    preco: 32.00,
  },
  {
    id: 7,
    titulo: "Homem-Aranha: A Última Caçada de Kraven",
    editora: "Marvel Comics",
    numero: 293,
    saga: "A Última Caçada de Kraven",
    heroi: "Homem-Aranha",
    autor: "J. M. DeMatteis",
    anoPublicacao: 1987,
    preco: 30.00,
  },
  {
    id: 8,
    titulo: "Saga da Fênix Negra",
    editora: "Marvel Comics",
    numero: 134,
    saga: "Saga da Fênix Negra",
    heroi: "X-Men",
    autor: "Chris Claremont",
    anoPublicacao: 1980,
    preco: 42.00,
  },
  {
    id: 9,
    titulo: "A Piada Mortal",
    editora: "DC Comics",
    numero: null,
    saga: "A Piada Mortal",
    heroi: "Coringa",
    autor: "Alan Moore",
    anoPublicacao: 1988,
    preco: 38.90,
  },
  {
    id: 10,
    titulo: "Reino do Amanhã",
    editora: "DC Comics",
    numero: 1,
    saga: "Reino do Amanhã",
    heroi: "Superman",
    autor: "Mark Waid",
    anoPublicacao: 1996,
    preco: 47.50,
  },
]

export default {quadrinhos}